package com.finsavvy.api.finsavvy_api.v1.seeders;

import com.finsavvy.api.finsavvy_api.v1.entities.account.CountryCurrency;
import com.finsavvy.api.finsavvy_api.v1.repositories.CountryCurrencyRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import java.util.Set;

@Component
@Order(2) 
@Slf4j
@RequiredArgsConstructor
public class CountryCurrencySeeder implements CommandLineRunner {

    private final CountryCurrencyRepository countryCurrencyRepository;

    @Override
    public void run(String... args) throws Exception {
        seedCountryCurrencies();
    }

    private void seedCountryCurrencies() {
        if (countryCurrencyRepository.count() == 0) {
            log.info("Seeding CountryCurrency");

            Set<CountryCurrency> countries = Set.of(
                    CountryCurrency.builder().countryName("Afghanistan").iso("AF").iso3("AFG").dialExtension("93").currencyCode("AFN").currencySymbol("\u060b").currencyName("Afghan afghani").build(),
                    CountryCurrency.builder().countryName("Albania").iso("AL").iso3("ALB").dialExtension("355").currencyCode("ALL").currencySymbol("L").currencyName("Albanian lek").build(),
                    CountryCurrency.builder().countryName("Algeria").iso("DZ").iso3("DZA").dialExtension("213").currencyCode("DZD").currencySymbol("\u062f.\u062c").currencyName("Algerian dinar").build(),
                    CountryCurrency.builder().countryName("Andorra").iso("AD").iso3("AND").dialExtension("376").currencyCode("EUR").currencySymbol("\u20ac").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Angola").iso("AO").iso3("AGO").dialExtension("244").currencyCode("AOA").currencySymbol("Kz").currencyName("Angolan kwanza").build(),
                    CountryCurrency.builder().countryName("Antigua and Barbuda").iso("AG").iso3("ATG").dialExtension("1").currencyCode("XCD").currencySymbol("$").currencyName("East Caribbean dollar").build(),
                    CountryCurrency.builder().countryName("Argentina").iso("AR").iso3("ARG").dialExtension("54").currencyCode("ARS").currencySymbol("$").currencyName("Argentine peso").build(),
                    CountryCurrency.builder().countryName("Armenia").iso("AM").iso3("ARM").dialExtension("374").currencyCode("AMD").currencySymbol("\u058f").currencyName("Armenian dram").build(),
                    CountryCurrency.builder().countryName("Australia").iso("AU").iso3("AUS").dialExtension("61").currencyCode("AUD").currencySymbol("$").currencyName("Australian dollar").build(),
                    CountryCurrency.builder().countryName("Austria").iso("AT").iso3("AUT").dialExtension("43").currencyCode("EUR").currencySymbol("\u20ac").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Azerbaijan").iso("AZ").iso3("AZE").dialExtension("994").currencyCode("AZN").currencySymbol("\u20bc").currencyName("Azerbaijani manat").build(),
                    CountryCurrency.builder().countryName("Bahamas").iso("BS").iso3("BHS").dialExtension("1").currencyCode("BSD").currencySymbol("$").currencyName("Bahamian dollar").build(),
                    CountryCurrency.builder().countryName("Bahrain").iso("BH").iso3("BHR").dialExtension("973").currencyCode("BHD").currencySymbol(".\u062f.\u0628").currencyName("Bahraini dinar").build(),
                    CountryCurrency.builder().countryName("Bangladesh").iso("BD").iso3("BGD").dialExtension("880").currencyCode("BDT").currencySymbol("\u09f3").currencyName("Bangladeshi taka").build(),
                    CountryCurrency.builder().countryName("Barbados").iso("BB").iso3("BRB").dialExtension("1").currencyCode("BBD").currencySymbol("$").currencyName("Barbadian dollar").build(),
                    CountryCurrency.builder().countryName("Belarus").iso("BY").iso3("BLR").dialExtension("375").currencyCode("BYN").currencySymbol("Br").currencyName("Belarusian ruble").build(),
                    CountryCurrency.builder().countryName("Belgium").iso("BE").iso3("BEL").dialExtension("32").currencyCode("EUR").currencySymbol("\u20ac").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Belize").iso("BZ").iso3("BLZ").dialExtension("501").currencyCode("BZD").currencySymbol("$").currencyName("Belize dollar").build(),
                    CountryCurrency.builder().countryName("Benin").iso("BJ").iso3("BEN").dialExtension("229").currencyCode("XOF").currencySymbol("Fr").currencyName("West African CFA franc").build(),
                    CountryCurrency.builder().countryName("Bhutan").iso("BT").iso3("BTN").dialExtension("975").currencyCode("BTN").currencySymbol("Nu.").currencyName("Bhutanese ngultrum").build(),
                    CountryCurrency.builder().countryName("Bolivia").iso("BO").iso3("BOL").dialExtension("591").currencyCode("BOB").currencySymbol("Bs.").currencyName("Bolivian boliviano").build(),
                    CountryCurrency.builder().countryName("Bosnia and Herzegovina").iso("BA").iso3("BIH").dialExtension("387").currencyCode("BAM").currencySymbol("KM").currencyName("Bosnia and Herzegovina convertible mark").build(),
                    CountryCurrency.builder().countryName("Botswana").iso("BW").iso3("BWA").dialExtension("267").currencyCode("BWP").currencySymbol("P").currencyName("Botswana pula").build(),
                    CountryCurrency.builder().countryName("Brazil").iso("BR").iso3("BRA").dialExtension("55").currencyCode("BRL").currencySymbol("R$").currencyName("Brazilian real").build(),
                    CountryCurrency.builder().countryName("Brunei").iso("BN").iso3("BRN").dialExtension("673").currencyCode("BND").currencySymbol("$").currencyName("Brunei dollar").build(),
                    CountryCurrency.builder().countryName("Bulgaria").iso("BG").iso3("BGR").dialExtension("359").currencyCode("BGN").currencySymbol("\u043b\u0432").currencyName("Bulgarian lev").build(),
                    CountryCurrency.builder().countryName("Burkina Faso").iso("BF").iso3("BFA").dialExtension("226").currencyCode("XOF").currencySymbol("Fr").currencyName("West African CFA franc").build(),
                    CountryCurrency.builder().countryName("Burundi").iso("BI").iso3("BDI").dialExtension("257").currencyCode("BIF").currencySymbol("Fr").currencyName("Burundian franc").build(),
                    CountryCurrency.builder().countryName("Cape Verde").iso("CV").iso3("CPV").dialExtension("238").currencyCode("CVE").currencySymbol("Esc").currencyName("Cape Verdean escudo").build(),
                    CountryCurrency.builder().countryName("Cambodia").iso("KH").iso3("KHM").dialExtension("855").currencyCode("KHR").currencySymbol("\u17db").currencyName("Cambodian riel").build(),
                    CountryCurrency.builder().countryName("Cameroon").iso("CM").iso3("CMR").dialExtension("237").currencyCode("XAF").currencySymbol("Fr").currencyName("Central African CFA franc").build(),
                    CountryCurrency.builder().countryName("Canada").iso("CA").iso3("CAN").dialExtension("1").currencyCode("CAD").currencySymbol("$").currencyName("Canadian dollar").build(),
                    CountryCurrency.builder().countryName("Central African Republic").iso("CF").iso3("CAF").dialExtension("236").currencyCode("XAF").currencySymbol("Fr").currencyName("Central African CFA franc").build(),
                    CountryCurrency.builder().countryName("Chad").iso("TD").iso3("TCD").dialExtension("235").currencyCode("XAF").currencySymbol("Fr").currencyName("Central African CFA franc").build(),
                    CountryCurrency.builder().countryName("Chile").iso("CL").iso3("CHL").dialExtension("56").currencyCode("CLP").currencySymbol("$").currencyName("Chilean peso").build(),
                    CountryCurrency.builder().countryName("China").iso("CN").iso3("CHN").dialExtension("86").currencyCode("CNY").currencySymbol("\u00a5").currencyName("Chinese yuan").build(),
                    CountryCurrency.builder().countryName("Colombia").iso("CO").iso3("COL").dialExtension("57").currencyCode("COP").currencySymbol("$").currencyName("Colombian peso").build(),
                    CountryCurrency.builder().countryName("Comoros").iso("KM").iso3("COM").dialExtension("269").currencyCode("KMF").currencySymbol("Fr").currencyName("Comorian franc").build(),
                    CountryCurrency.builder().countryName("Congo (Brazzaville)").iso("CG").iso3("COG").dialExtension("242").currencyCode("XAF").currencySymbol("Fr").currencyName("Central African CFA franc").build(),
                    CountryCurrency.builder().countryName("Congo (Kinshasa) (DR Congo)").iso("CD").iso3("COD").dialExtension("243").currencyCode("CDF").currencySymbol("Fr").currencyName("Congolese franc").build(),
                    CountryCurrency.builder().countryName("Costa Rica").iso("CR").iso3("CRI").dialExtension("506").currencyCode("CRC").currencySymbol("\u20a1").currencyName("Costa Rican col\u00f3n").build(),
                    CountryCurrency.builder().countryName("Croatia").iso("HR").iso3("HRV").dialExtension("385").currencyCode("HRK").currencySymbol("kn").currencyName("Croatian kuna").build(),
                    CountryCurrency.builder().countryName("Cuba").iso("CU").iso3("CUB").dialExtension("53").currencyCode("CUP").currencySymbol("$").currencyName("Cuban peso").build(),
                    CountryCurrency.builder().countryName("Cyprus").iso("CY").iso3("CYP").dialExtension("357").currencyCode("EUR").currencySymbol("\u20ac").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Czech Republic").iso("CZ").iso3("CZE").dialExtension("420").currencyCode("CZK").currencySymbol("K\u010d").currencyName("Czech koruna").build(),
                    CountryCurrency.builder().countryName("Denmark").iso("DK").iso3("DNK").dialExtension("45").currencyCode("DKK").currencySymbol("kr").currencyName("Danish krone").build(),
                    CountryCurrency.builder().countryName("Djibouti").iso("DJ").iso3("DJI").dialExtension("253").currencyCode("DJF").currencySymbol("Fr").currencyName("Djiboutian franc").build(),
                    CountryCurrency.builder().countryName("Dominica").iso("DM").iso3("DMA").dialExtension("1").currencyCode("XCD").currencySymbol("$").currencyName("East Caribbean dollar").build(),
                    CountryCurrency.builder().countryName("Dominican Republic").iso("DO").iso3("DOM").dialExtension("1").currencyCode("DOP").currencySymbol("$").currencyName("Dominican peso").build(),
                    CountryCurrency.builder().countryName("East Timor (Timor-Leste)").iso("TL").iso3("TLS").dialExtension("670").currencyCode("USD").currencySymbol("$").currencyName("United States dollar").build(),
                    CountryCurrency.builder().countryName("Ecuador").iso("EC").iso3("ECU").dialExtension("593").currencyCode("USD").currencySymbol("$").currencyName("United States dollar").build(),
                    CountryCurrency.builder().countryName("Egypt").iso("EG").iso3("EGY").dialExtension("20").currencyCode("EGP").currencySymbol("\u00a3").currencyName("Egyptian pound").build(),
                    CountryCurrency.builder().countryName("El Salvador").iso("SV").iso3("SLV").dialExtension("503").currencyCode("USD").currencySymbol("$").currencyName("United States dollar").build(),
                    CountryCurrency.builder().countryName("Equatorial Guinea").iso("GQ").iso3("GNQ").dialExtension("240").currencyCode("XAF").currencySymbol("Fr").currencyName("Central African CFA franc").build(),
                    CountryCurrency.builder().countryName("Eritrea").iso("ER").iso3("ERI").dialExtension("291").currencyCode("ERN").currencySymbol("Nfk").currencyName("Eritrean nakfa").build(),
                    CountryCurrency.builder().countryName("Estonia").iso("EE").iso3("EST").dialExtension("372").currencyCode("EUR").currencySymbol("\u20ac").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Eswatini (Swaziland)").iso("SZ").iso3("SWZ").dialExtension("268").currencyCode("SZL").currencySymbol("L").currencyName("Swazi lilangeni").build(),
                    CountryCurrency.builder().countryName("Ethiopia").iso("ET").iso3("ETH").dialExtension("251").currencyCode("ETB").currencySymbol("Br").currencyName("Ethiopian birr").build(),
                    CountryCurrency.builder().countryName("Fiji").iso("FJ").iso3("FJI").dialExtension("679").currencyCode("FJD").currencySymbol("$").currencyName("Fijian dollar").build(),
                    CountryCurrency.builder().countryName("Finland").iso("FI").iso3("FIN").dialExtension("358").currencyCode("EUR").currencySymbol("\u20ac").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("France").iso("FR").iso3("FRA").dialExtension("33").currencyCode("EUR").currencySymbol("\u20ac").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Gabon").iso("GA").iso3("GAB").dialExtension("241").currencyCode("XAF").currencySymbol("Fr").currencyName("Central African CFA franc").build(),
                    CountryCurrency.builder().countryName("Gambia").iso("GM").iso3("GMB").dialExtension("220").currencyCode("GMD").currencySymbol("D").currencyName("Gambian dalasi").build(),
                    CountryCurrency.builder().countryName("Georgia").iso("GE").iso3("GEO").dialExtension("995").currencyCode("GEL").currencySymbol("\u20be").currencyName("Georgian lari").build(),
                    CountryCurrency.builder().countryName("Germany").iso("DE").iso3("DEU").dialExtension("49").currencyCode("EUR").currencySymbol("\u20ac").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Ghana").iso("GH").iso3("GHA").dialExtension("233").currencyCode("GHS").currencySymbol("\u20b5").currencyName("Ghanaian cedi").build(),
                    CountryCurrency.builder().countryName("Greece").iso("GR").iso3("GRC").dialExtension("30").currencyCode("EUR").currencySymbol("\u20ac").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Grenada").iso("GD").iso3("GRD").dialExtension("1").currencyCode("XCD").currencySymbol("$").currencyName("East Caribbean dollar").build(),
                    CountryCurrency.builder().countryName("Guatemala").iso("GT").iso3("GTM").dialExtension("502").currencyCode("GTQ").currencySymbol("Q").currencyName("Guatemalan quetzal").build(),
                    CountryCurrency.builder().countryName("Guinea").iso("GN").iso3("GIN").dialExtension("224").currencyCode("GNF").currencySymbol("Fr").currencyName("Guinean franc").build(),
                    CountryCurrency.builder().countryName("Guinea-Bissau").iso("GW").iso3("GNB").dialExtension("245").currencyCode("XOF").currencySymbol("Fr").currencyName("West African CFA franc").build(),
                    CountryCurrency.builder().countryName("Guyana").iso("GY").iso3("GUY").dialExtension("592").currencyCode("GYD").currencySymbol("$").currencyName("Guyanese dollar").build(),
                    CountryCurrency.builder().countryName("Haiti").iso("HT").iso3("HTI").dialExtension("509").currencyCode("HTG").currencySymbol("G").currencyName("Haitian gourde").build(),
                    CountryCurrency.builder().countryName("Honduras").iso("HN").iso3("HND").dialExtension("504").currencyCode("HNL").currencySymbol("L").currencyName("Honduran lempira").build(),
                    CountryCurrency.builder().countryName("Hungary").iso("HU").iso3("HUN").dialExtension("36").currencyCode("HUF").currencySymbol("Ft").currencyName("Hungarian forint").build(),
                    CountryCurrency.builder().countryName("Iceland").iso("IS").iso3("ISL").dialExtension("354").currencyCode("ISK").currencySymbol("kr").currencyName("Icelandic kr\u00f3na").build(),
                    CountryCurrency.builder().countryName("India").iso("IN").iso3("IND").dialExtension("91").currencyCode("INR").currencySymbol("\u20b9").currencyName("Indian rupee").build(),
                    CountryCurrency.builder().countryName("Indonesia").iso("ID").iso3("IDN").dialExtension("62").currencyCode("IDR").currencySymbol("Rp").currencyName("Indonesian rupiah").build(),
                    CountryCurrency.builder().countryName("Iran").iso("IR").iso3("IRN").dialExtension("98").currencyCode("IRR").currencySymbol("\ufdfc").currencyName("Iranian rial").build(),
                    CountryCurrency.builder().countryName("Iraq").iso("IQ").iso3("IRQ").dialExtension("964").currencyCode("IQD").currencySymbol("\u0639.\u062f").currencyName("Iraqi dinar").build(),
                    CountryCurrency.builder().countryName("Ireland").iso("IE").iso3("IRL").dialExtension("353").currencyCode("EUR").currencySymbol("\u20ac").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Israel").iso("IL").iso3("ISR").dialExtension("972").currencyCode("ILS").currencySymbol("\u20aa").currencyName("Israeli new shekel").build(),
                    CountryCurrency.builder().countryName("Italy").iso("IT").iso3("ITA").dialExtension("39").currencyCode("EUR").currencySymbol("\u20ac").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Ivory Coast (C\u00f4te d'Ivoire)").iso("CI").iso3("CIV").dialExtension("225").currencyCode("XOF").currencySymbol("Fr").currencyName("West African CFA franc").build(),
                    CountryCurrency.builder().countryName("Jamaica").iso("JM").iso3("JAM").dialExtension("1").currencyCode("JMD").currencySymbol("$").currencyName("Jamaican dollar").build(),
                    CountryCurrency.builder().countryName("Japan").iso("JP").iso3("JPN").dialExtension("81").currencyCode("JPY").currencySymbol("\u00a5").currencyName("Japanese yen").build(),
                    CountryCurrency.builder().countryName("Jordan").iso("JO").iso3("JOR").dialExtension("962").currencyCode("JOD").currencySymbol("\u062f.\u0627").currencyName("Jordanian dinar").build(),
                    CountryCurrency.builder().countryName("Kazakhstan").iso("KZ").iso3("KAZ").dialExtension("7").currencyCode("KZT").currencySymbol("\u20b8").currencyName("Kazakhstani tenge").build(),
                    CountryCurrency.builder().countryName("Kenya").iso("KE").iso3("KEN").dialExtension("254").currencyCode("KES").currencySymbol("Sh").currencyName("Kenyan shilling").build(),
                    CountryCurrency.builder().countryName("Kiribati").iso("KI").iso3("KIR").dialExtension("686").currencyCode("AUD").currencySymbol("$").currencyName("Australian dollar").build(),
                    CountryCurrency.builder().countryName("Kosovo").iso("XK").iso3("XKK").dialExtension("383").currencyCode("EUR").currencySymbol("\u20ac").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Kuwait").iso("KW").iso3("KWT").dialExtension("965").currencyCode("KWD").currencySymbol("\u062f.\u0643").currencyName("Kuwaiti dinar").build(),
                    CountryCurrency.builder().countryName("Kyrgyzstan").iso("KG").iso3("KGZ").dialExtension("996").currencyCode("KGS").currencySymbol("\u0441").currencyName("Kyrgyzstani som").build(),
                    CountryCurrency.builder().countryName("Laos").iso("LA").iso3("LAO").dialExtension("856").currencyCode("LAK").currencySymbol("\u20ad").currencyName("Laotian kip").build(),
                    CountryCurrency.builder().countryName("Latvia").iso("LV").iso3("LVA").dialExtension("371").currencyCode("EUR").currencySymbol("\u20ac").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Lebanon").iso("LB").iso3("LBN").dialExtension("961").currencyCode("LBP").currencySymbol("\u0644.\u0644").currencyName("Lebanese pound").build(),
                    CountryCurrency.builder().countryName("Lesotho").iso("LS").iso3("LSO").dialExtension("266").currencyCode("LSL").currencySymbol("L").currencyName("Lesotho loti").build(),
                    CountryCurrency.builder().countryName("Liberia").iso("LR").iso3("LBR").dialExtension("231").currencyCode("LRD").currencySymbol("$").currencyName("Liberian dollar").build(),
                    CountryCurrency.builder().countryName("Libya").iso("LY").iso3("LBY").dialExtension("218").currencyCode("LYD").currencySymbol("\u0644.\u062f").currencyName("Libyan dinar").build(),
                    CountryCurrency.builder().countryName("Liechtenstein").iso("LI").iso3("LIE").dialExtension("423").currencyCode("CHF").currencySymbol("Fr").currencyName("Swiss franc").build(),
                    CountryCurrency.builder().countryName("Lithuania").iso("LT").iso3("LTU").dialExtension("370").currencyCode("EUR").currencySymbol("\u20ac").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Luxembourg").iso("LU").iso3("LUX").dialExtension("352").currencyCode("EUR").currencySymbol("\u20ac").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Madagascar").iso("MG").iso3("MDG").dialExtension("261").currencyCode("MGA").currencySymbol("Ar").currencyName("Malagasy ariary").build(),
                    CountryCurrency.builder().countryName("Malawi").iso("MW").iso3("MWI").dialExtension("265").currencyCode("MWK").currencySymbol("MK").currencyName("Malawian kwacha").build(),
                    CountryCurrency.builder().countryName("Malaysia").iso("MY").iso3("MYS").dialExtension("60").currencyCode("MYR").currencySymbol("RM").currencyName("Malaysian ringgit").build(),
                    CountryCurrency.builder().countryName("Maldives").iso("MV").iso3("MDV").dialExtension("960").currencyCode("MVR").currencySymbol(".\u0783").currencyName("Maldivian rufiyaa").build(),
                    CountryCurrency.builder().countryName("Mali").iso("ML").iso3("MLI").dialExtension("223").currencyCode("XOF").currencySymbol("Fr").currencyName("West African CFA franc").build(),
                    CountryCurrency.builder().countryName("Malta").iso("MT").iso3("MLT").dialExtension("356").currencyCode("EUR").currencySymbol("\u20ac").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Marshall Islands").iso("MH").iso3("MHL").dialExtension("692").currencyCode("USD").currencySymbol("$").currencyName("United States dollar").build(),
                    CountryCurrency.builder().countryName("Mauritania").iso("MR").iso3("MRT").dialExtension("222").currencyCode("MRU").currencySymbol("UM").currencyName("Mauritanian ouguiya").build(),
                    CountryCurrency.builder().countryName("Mauritius").iso("MU").iso3("MUS").dialExtension("230").currencyCode("MUR").currencySymbol("\u20a8").currencyName("Mauritian rupee").build(),
                    CountryCurrency.builder().countryName("Mexico").iso("MX").iso3("MEX").dialExtension("52").currencyCode("MXN").currencySymbol("$").currencyName("Mexican peso").build(),
                    CountryCurrency.builder().countryName("Micronesia").iso("FM").iso3("FSM").dialExtension("691").currencyCode("USD").currencySymbol("$").currencyName("United States dollar").build(),
                    CountryCurrency.builder().countryName("Moldova").iso("MD").iso3("MDA").dialExtension("373").currencyCode("MDL").currencySymbol("L").currencyName("Moldovan leu").build(),
                    CountryCurrency.builder().countryName("Monaco").iso("MC").iso3("MCO").dialExtension("377").currencyCode("EUR").currencySymbol("\u20ac").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Mongolia").iso("MN").iso3("MNG").dialExtension("976").currencyCode("MNT").currencySymbol("\u20ae").currencyName("Mongolian t\u00f6gr\u00f6g").build(),
                    CountryCurrency.builder().countryName("Montenegro").iso("ME").iso3("MNE").dialExtension("382").currencyCode("EUR").currencySymbol("\u20ac").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Morocco").iso("MA").iso3("MAR").dialExtension("212").currencyCode("MAD").currencySymbol("\u062f.\u0645.").currencyName("Moroccan dirham").build(),
                    CountryCurrency.builder().countryName("Mozambique").iso("MZ").iso3("MOZ").dialExtension("258").currencyCode("MZN").currencySymbol("MT").currencyName("Mozambican metical").build(),
                    CountryCurrency.builder().countryName("Myanmar (Burma)").iso("MM").iso3("MMR").dialExtension("95").currencyCode("MMK").currencySymbol("Ks").currencyName("Burmese kyat").build(),
                    CountryCurrency.builder().countryName("Namibia").iso("NA").iso3("NAM").dialExtension("264").currencyCode("NAD").currencySymbol("$").currencyName("Namibian dollar").build(),
                    CountryCurrency.builder().countryName("Nauru").iso("NR").iso3("NRU").dialExtension("674").currencyCode("AUD").currencySymbol("$").currencyName("Australian dollar").build(),
                    CountryCurrency.builder().countryName("Nepal").iso("NP").iso3("NPL").dialExtension("977").currencyCode("NPR").currencySymbol("\u20a8").currencyName("Nepalese rupee").build(),
                    CountryCurrency.builder().countryName("Netherlands").iso("NL").iso3("NLD").dialExtension("31").currencyCode("EUR").currencySymbol("\u20ac").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("New Zealand").iso("NZ").iso3("NZL").dialExtension("64").currencyCode("NZD").currencySymbol("$").currencyName("New Zealand dollar").build(),
                    CountryCurrency.builder().countryName("Nicaragua").iso("NI").iso3("NIC").dialExtension("505").currencyCode("NIO").currencySymbol("C$").currencyName("Nicaraguan c\u00f3rdoba").build(),
                    CountryCurrency.builder().countryName("Niger").iso("NE").iso3("NER").dialExtension("227").currencyCode("XOF").currencySymbol("Fr").currencyName("West African CFA franc").build(),
                    CountryCurrency.builder().countryName("Nigeria").iso("NG").iso3("NGA").dialExtension("234").currencyCode("NGN").currencySymbol("\u20a6").currencyName("Nigerian naira").build(),
                    CountryCurrency.builder().countryName("North Korea").iso("KP").iso3("PRK").dialExtension("850").currencyCode("KPW").currencySymbol("\u20a9").currencyName("North Korean won").build(),
                    CountryCurrency.builder().countryName("North Macedonia").iso("MK").iso3("MKD").dialExtension("389").currencyCode("MKD").currencySymbol("\u0434\u0435\u043d").currencyName("Macedonian denar").build(),
                    CountryCurrency.builder().countryName("Norway").iso("NO").iso3("NOR").dialExtension("47").currencyCode("NOK").currencySymbol("kr").currencyName("Norwegian krone").build(),
                    CountryCurrency.builder().countryName("Oman").iso("OM").iso3("OMN").dialExtension("968").currencyCode("OMR").currencySymbol("\u0631.\u0639.").currencyName("Omani rial").build(),
                    CountryCurrency.builder().countryName("Pakistan").iso("PK").iso3("PAK").dialExtension("92").currencyCode("PKR").currencySymbol("\u20a8").currencyName("Pakistani rupee").build(),
                    CountryCurrency.builder().countryName("Palau").iso("PW").iso3("PLW").dialExtension("680").currencyCode("USD").currencySymbol("$").currencyName("United States dollar").build(),
                    CountryCurrency.builder().countryName("Panama").iso("PA").iso3("PAN").dialExtension("507").currencyCode("PAB").currencySymbol("B/.").currencyName("Panamanian balboa").build(),
                    CountryCurrency.builder().countryName("Papua New Guinea").iso("PG").iso3("PNG").dialExtension("675").currencyCode("PGK").currencySymbol("K").currencyName("Papua New Guinean kina").build(),
                    CountryCurrency.builder().countryName("Paraguay").iso("PY").iso3("PRY").dialExtension("595").currencyCode("PYG").currencySymbol("₲").currencyName("Paraguayan guaraní").build(),
                    CountryCurrency.builder().countryName("Peru").iso("PE").iso3("PER").dialExtension("51").currencyCode("PEN").currencySymbol("S/").currencyName("Peruvian sol").build(),
                    CountryCurrency.builder().countryName("Philippines").iso("PH").iso3("PHL").dialExtension("63").currencyCode("PHP").currencySymbol("₱").currencyName("Philippine peso").build(),
                    CountryCurrency.builder().countryName("Poland").iso("PL").iso3("POL").dialExtension("48").currencyCode("PLN").currencySymbol("zł").currencyName("Polish złoty").build(),
                    CountryCurrency.builder().countryName("Portugal").iso("PT").iso3("PRT").dialExtension("351").currencyCode("EUR").currencySymbol("€").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Qatar").iso("QA").iso3("QAT").dialExtension("974").currencyCode("QAR").currencySymbol("ر.ق").currencyName("Qatari riyal").build(),
                    CountryCurrency.builder().countryName("Romania").iso("RO").iso3("ROU").dialExtension("40").currencyCode("RON").currencySymbol("lei").currencyName("Romanian leu").build(),
                    CountryCurrency.builder().countryName("Russia").iso("RU").iso3("RUS").dialExtension("7").currencyCode("RUB").currencySymbol("₽").currencyName("Russian ruble").build(),
                    CountryCurrency.builder().countryName("Rwanda").iso("RW").iso3("RWA").dialExtension("250").currencyCode("RWF").currencySymbol("Fr").currencyName("Rwandan franc").build(),
                    CountryCurrency.builder().countryName("Saint Kitts and Nevis").iso("KN").iso3("KNA").dialExtension("1").currencyCode("XCD").currencySymbol("$").currencyName("East Caribbean dollar").build(),
                    CountryCurrency.builder().countryName("Saint Lucia").iso("LC").iso3("LCA").dialExtension("1").currencyCode("XCD").currencySymbol("$").currencyName("East Caribbean dollar").build(),
                    CountryCurrency.builder().countryName("Saint Vincent and the Grenadines").iso("VC").iso3("VCT").dialExtension("1").currencyCode("XCD").currencySymbol("$").currencyName("East Caribbean dollar").build(),
                    CountryCurrency.builder().countryName("Samoa").iso("WS").iso3("WSM").dialExtension("685").currencyCode("WST").currencySymbol("T").currencyName("Samoan tālā").build(),
                    CountryCurrency.builder().countryName("San Marino").iso("SM").iso3("SMR").dialExtension("378").currencyCode("EUR").currencySymbol("€").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("São Tomé and Príncipe").iso("ST").iso3("STP").dialExtension("239").currencyCode("STN").currencySymbol("Db").currencyName("São Tomé and Príncipe dobra").build(),
                    CountryCurrency.builder().countryName("Saudi Arabia").iso("SA").iso3("SAU").dialExtension("966").currencyCode("SAR").currencySymbol("ر.س").currencyName("Saudi riyal").build(),
                    CountryCurrency.builder().countryName("Senegal").iso("SN").iso3("SEN").dialExtension("221").currencyCode("XOF").currencySymbol("Fr").currencyName("West African CFA franc").build(),
                    CountryCurrency.builder().countryName("Serbia").iso("RS").iso3("SRB").dialExtension("381").currencyCode("RSD").currencySymbol("дин").currencyName("Serbian dinar").build(),
                    CountryCurrency.builder().countryName("Seychelles").iso("SC").iso3("SYC").dialExtension("248").currencyCode("SCR").currencySymbol("₨").currencyName("Seychellois rupee").build(),
                    CountryCurrency.builder().countryName("Sierra Leone").iso("SL").iso3("SLE").dialExtension("232").currencyCode("SLL").currencySymbol("Le").currencyName("Sierra Leonean leone").build(),
                    CountryCurrency.builder().countryName("Singapore").iso("SG").iso3("SGP").dialExtension("65").currencyCode("SGD").currencySymbol("$").currencyName("Singapore dollar").build(),
                    CountryCurrency.builder().countryName("Slovakia").iso("SK").iso3("SVK").dialExtension("421").currencyCode("EUR").currencySymbol("€").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Slovenia").iso("SI").iso3("SVN").dialExtension("386").currencyCode("EUR").currencySymbol("€").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Solomon Islands").iso("SB").iso3("SLB").dialExtension("677").currencyCode("SBD").currencySymbol("$").currencyName("Solomon Islands dollar").build(),
                    CountryCurrency.builder().countryName("Somalia").iso("SO").iso3("SOM").dialExtension("252").currencyCode("SOS").currencySymbol("Sh").currencyName("Somali shilling").build(),
                    CountryCurrency.builder().countryName("South Africa").iso("ZA").iso3("ZAF").dialExtension("27").currencyCode("ZAR").currencySymbol("R").currencyName("South African rand").build(),
                    CountryCurrency.builder().countryName("South Korea").iso("KR").iso3("KOR").dialExtension("82").currencyCode("KRW").currencySymbol("₩").currencyName("South Korean won").build(),
                    CountryCurrency.builder().countryName("South Sudan").iso("SS").iso3("SSD").dialExtension("211").currencyCode("SSP").currencySymbol("£").currencyName("South Sudanese pound").build(),
                    CountryCurrency.builder().countryName("Spain").iso("ES").iso3("ESP").dialExtension("34").currencyCode("EUR").currencySymbol("€").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Sri Lanka").iso("LK").iso3("LKA").dialExtension("94").currencyCode("LKR").currencySymbol("₨").currencyName("Sri Lankan rupee").build(),
                    CountryCurrency.builder().countryName("Sudan").iso("SD").iso3("SDN").dialExtension("249").currencyCode("SDG").currencySymbol("ج.س").currencyName("Sudanese pound").build(),
                    CountryCurrency.builder().countryName("Suriname").iso("SR").iso3("SUR").dialExtension("597").currencyCode("SRD").currencySymbol("$").currencyName("Surinamese dollar").build(),
                    CountryCurrency.builder().countryName("Sweden").iso("SE").iso3("SWE").dialExtension("46").currencyCode("SEK").currencySymbol("kr").currencyName("Swedish krona").build(),
                    CountryCurrency.builder().countryName("Switzerland").iso("CH").iso3("CHE").dialExtension("41").currencyCode("CHF").currencySymbol("Fr").currencyName("Swiss franc").build(),
                    CountryCurrency.builder().countryName("Syria").iso("SY").iso3("SYR").dialExtension("963").currencyCode("SYP").currencySymbol("£ ").currencyName("Syrian pound").build(),
                    CountryCurrency.builder().countryName("Taiwan").iso("TW").iso3("TWN").dialExtension("886").currencyCode("TWD").currencySymbol("$").currencyName("New Taiwan dollar").build(),
                    CountryCurrency.builder().countryName("Tajikistan").iso("TJ").iso3("TJK").dialExtension("992").currencyCode("TJS").currencySymbol("ЅМ").currencyName("Tajikistani somoni").build(),
                    CountryCurrency.builder().countryName("Tanzania").iso("TZ").iso3("TZA").dialExtension("255").currencyCode("TZS").currencySymbol("Sh").currencyName("Tanzanian shilling").build(),
                    CountryCurrency.builder().countryName("Thailand").iso("TH").iso3("THA").dialExtension("66").currencyCode("THB").currencySymbol("฿").currencyName("Thai baht").build(),
                    CountryCurrency.builder().countryName("Togo").iso("TG").iso3("TGO").dialExtension("228").currencyCode("XOF").currencySymbol("Fr").currencyName("West African CFA franc").build(),
                    CountryCurrency.builder().countryName("Tonga").iso("TO").iso3("TON").dialExtension("676").currencyCode("TOP").currencySymbol("T$").currencyName("Tongan paʻanga").build(),
                    CountryCurrency.builder().countryName("Trinidad and Tobago").iso("TT").iso3("TTO").dialExtension("1").currencyCode("TTD").currencySymbol("$").currencyName("Trinidad and Tobago dollar").build(),
                    CountryCurrency.builder().countryName("Tunisia").iso("TN").iso3("TUN").dialExtension("216").currencyCode("TND").currencySymbol("د.ت").currencyName("Tunisian dinar").build(),
                    CountryCurrency.builder().countryName("Turkey").iso("TR").iso3("TUR").dialExtension("90").currencyCode("TRY").currencySymbol("₺").currencyName("Turkish lira").build(),
                    CountryCurrency.builder().countryName("Turkmenistan").iso("TM").iso3("TKM").dialExtension("993").currencyCode("TMT").currencySymbol("m").currencyName("Turkmenistan manat").build(),
                    CountryCurrency.builder().countryName("Tuvalu").iso("TV").iso3("TUV").dialExtension("688").currencyCode("AUD").currencySymbol("$").currencyName("Australian dollar").build(),
                    CountryCurrency.builder().countryName("Uganda").iso("UG").iso3("UGA").dialExtension("256").currencyCode("UGX").currencySymbol("USh").currencyName("Ugandan shilling").build(),
                    CountryCurrency.builder().countryName("Ukraine").iso("UA").iso3("UKR").dialExtension("380").currencyCode("UAH").currencySymbol("₴").currencyName("Ukrainian hryvnia").build(),
                    CountryCurrency.builder().countryName("United Arab Emirates").iso("AE").iso3("ARE").dialExtension("971").currencyCode("AED").currencySymbol("د.إ").currencyName("United Arab Emirates dirham").build(),
                    CountryCurrency.builder().countryName("United Kingdom").iso("GB").iso3("GBR").dialExtension("44").currencyCode("GBP").currencySymbol("£").currencyName("British pound sterling").build(),
                    CountryCurrency.builder().countryName("United States").iso("US").iso3("USA").dialExtension("1").currencyCode("USD").currencySymbol("$").currencyName("United States dollar").build(),
                    CountryCurrency.builder().countryName("Uruguay").iso("UY").iso3("URY").dialExtension("598").currencyCode("UYU").currencySymbol("$").currencyName("Uruguayan peso").build(),
                    CountryCurrency.builder().countryName("Uzbekistan").iso("UZ").iso3("UZB").dialExtension("998").currencyCode("UZS").currencySymbol("soʼm").currencyName("Uzbekistani soʼm").build(),
                    CountryCurrency.builder().countryName("Vanuatu").iso("VU").iso3("VUT").dialExtension("678").currencyCode("VUV").currencySymbol("Vt").currencyName("Vanuatu vatu").build(),
                    CountryCurrency.builder().countryName("Holy See").iso("VA").iso3("VAT").dialExtension("379").currencyCode("EUR").currencySymbol("€").currencyName("Euro").build(),
                    CountryCurrency.builder().countryName("Venezuela").iso("VE").iso3("VEN").dialExtension("58").currencyCode("VES").currencySymbol("Bs").currencyName("Venezuelan bolívar").build(),
                    CountryCurrency.builder().countryName("Vietnam").iso("VN").iso3("VNM").dialExtension("84").currencyCode("VND").currencySymbol("₫").currencyName("Vietnamese đồng").build(),
                    CountryCurrency.builder().countryName("Yemen").iso("YE").iso3("YEM").dialExtension("967").currencyCode("YER").currencySymbol("﷼").currencyName("Yemeni rial").build(),
                    CountryCurrency.builder().countryName("Zambia").iso("ZM").iso3("ZMB").dialExtension("260").currencyCode("ZMW").currencySymbol("ZK").currencyName("Zambian kwacha").build(),
                    CountryCurrency.builder().countryName("Zimbabwe").iso("ZW").iso3("ZWE").dialExtension("263").currencyCode("ZWL").currencySymbol("$").currencyName("Zimbabwean dollar").build()
            );
            countryCurrencyRepository.saveAll(countries);
            log.info("{} CountryCurrency records seeded.", countries.size());
        } else {
            log.info("CountryCurrency data already exists. Skipping seed.");
        }
    }
}